// This file is generated by Firebase Studio.
import {initializeApp, getApp, getApps} from 'firebase/app';
import {getAuth} from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';
import { getPerformance } from "firebase/performance";
import { getStorage } from 'firebase/storage';

const firebaseConfig = {
  "projectId": "bizbalance-o2v9w",
  "appId": "1:151693194034:web:1f9505c9a66c1947f71d2b",
  "storageBucket": "bizbalance-o2v9w.firebasestorage.app",
  "apiKey": "AIzaSyA58s2PK9fQuIdZZQcKukLbCAHddYSRJds",
  "authDomain": "bizbalance-o2v9w.firebaseapp.com",
  "measurementId": "G-L9TC2Q43BN",
  "messagingSenderId": "151693194034"
};

// Singleton pattern to initialize Firebase
const app = getApps().length ? getApps()[0] : initializeApp(firebaseConfig);

const auth = getAuth(app);
const db = getFirestore(app);
const storage = getStorage(app);

// Initialize Performance Monitoring only on the client side
let perf;
if (typeof window !== 'undefined') {
  perf = getPerformance(app);
}

export {app, auth, db, perf, storage};